# Generated by Django 5.0.3 on 2024-12-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_advertisement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
